### ISSUE TITLE
File output example

### ISSUE THREAD

**Issue by mchelen** [mvtm-dn/cucumber-junit-formatter#5]
The syntax for outputting to a file is a little confusing, a working example is:
`cucumber-js -f node_modules/cucumber-junit-formatter:test-report.xml`

**Comment by mvtm-dn** [comment]
I'm just wondering what you mean 'The syntax for outputting is a little confusing'?
```
... node_modules/cucumber-junit-formattter[:<out_file>]
```
This definition means that you either specify out_file or use stdout if out_file is omitted. See [cucumber cl](/cucumber/cucumber-js/blob/master/docs/cli.md) for more

**Comment by mchelen** [comment]
Maybe it's just me but I kept trying things like:
`cucumber-js -f node_modules/cucumber-junit-formatter[:test-report.xml]`
`cucumber-js -f node_modules/cucumber-junit-formatter:<test-report.xml>`

That's confusing about the cucumber cli docs too though.

**Comment by mvtm-dn** [comment]
> Maybe it's just me but I kept trying things like:
> `cucumber-js -f node_modules/cucumber-junit-formatter[:test-report.xml]`
> `cucumber-js -f node_modules/cucumber-junit-formatter:<test-report.xml>`
> 
> That's confusing about the cucumber cli docs too though.
JFYI `[..]` means _optional_. So `cucumber-js -f node_modules/cucumber-junit-formatter[:test-report.xml]` means that you can use `cucumber-js -f node_modules/cucumber-junit-formatter` and got report on stdout or add `:` and filename and got report in this filename.

**Comment by mikeengland** [comment]
Hi there. Is it possible to specify a directory and a file instead of just a file? e.g. `./output/junit.xml`?

**Comment by mvtm-dn** [comment]
Shure

**Comment by mikeengland** [comment]
Thanks for confirming - I was having an issue with my Docker setup which was causing it to not work as I expected. All good now!
