### ISSUE TITLE
Bamboo JUnit Parser Task not merging the test cases

### ISSUE THREAD

**Issue by harishraok** [mvtm-dn/cucumber-junit-formatter#6]
Hi, 

When parsing the JUnit xml results in Bamboo its clubbing the test cases and not showing the proper test results. IS there any specific setting to be done for cucumber-junit-formatter to make the bamboo parser read properly?

Also how to provide the format options? I there an example?

Thanks.,
Harish Rao

**Comment by mvtm-dn** [comment]
could you please provide some examples. I never ever use bamboo so I need more information

**Comment by harishraok** [comment]
Hi, 
Thanks for a quick response.

**Results XML that Bamboo JUNIT Parser understands:** 
Feature is contained in single Test suite and Test cases contain feature and Scenario in Classname and name is the step details. 
Attached if the xml file as TXT bamboo-junit-parser-friendly.txt

[bamboo-junit-parser-friendly.txt](https://github.com/mvtm-dn/cucumber-junit-formatter/files/3737245/bamboo-junit-parser-friendly.txt)
[cucumber-junit-formatter.txt](https://github.com/mvtm-dn/cucumber-junit-formatter/files/3737246/cucumber-junit-formatter.txt)


**Using Cucumber-junit-formatter we get below XML** :  cucumber-junit-formatter.txt



Is there a way we can get XML format that Bamboo Parser undertands by using the cucumber-junit-formatter?

Appriciate your support. Let me know if you need more detials.

**Comment by mvtm-dn** [comment]
Thanks for examples. I'll look and try to fix this issue in next two-three day

**Comment by harishraok** [comment]
Thanks and appreciate your help. Let me know if you need any more
information from me.

**Comment by mvtm-dn** [comment]
I have a question. Looks like `cucumber-junit-fomatter.txt` from your example is not well-formed xml. So is this file was edit? 
And the second problem is that the atlassian's developers did not use any xsd to validate xml schema. They said that the this [xsd](https://github.com/behave/behave/blob/master/etc/junit.xml/junit-4.xsd) is closest to they scripts. So cucumber-json generated xml pass this schema

**Comment by harishraok** [comment]
Hello,

Attached is the full file. Can provide you with more information as needed.

-Harish

**Comment by mvtm-dn** [comment]
Unfortunately I can't reproduce issue. Also I see that the resulting junit file provided by you is not well-formed xml.

**Comment by mvtm-dn** [comment]
Can't reproduce
